; packaging/windows/protoskipper.iss — P6.C.1 of EXECUTION_PLAN.md
;
; Inno Setup 6 script for ProtoSkipper Windows installer.
;
; Usage (from this directory):
;   iscc protoskipper.iss
;
; Or via PowerShell build script:
;   pwsh packaging/windows/build_installer.ps1
;
; Prerequisites:
;   - Inno Setup 6  (https://jrsoftware.org/isdl.php)
;   - PyInstaller already run; frozen app in dist\ProtoSkipper\
;     (build_installer.ps1 handles this automatically)
;
; Optional code-signing:
;   Set the SIGNING_CERT env var to the .pfx path for signtool.
;   The SignTool declaration below is commented out by default.

#define MyAppName       "ProtoSkipper"
#define MyAppPublisher  "DataSailors Pvt Ltd"
#define MyAppURL        "https://github.com/datasailors/protoskipper"
#define MyAppExeName    "ProtoSkipper.exe"
; Read version from a file generated by build_installer.ps1
#define MyAppVersion    ReadIni(SourcePath + "\version.txt", "meta", "version", "0.0.0")

[Setup]
AppId={{8E3A7F2C-1B4D-4E9A-BB5C-2D7F6A3E8C91}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}/issues
AppUpdatesURL={#MyAppURL}/releases
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=..\..\LICENSE
OutputDir=..\..\dist
OutputBaseFilename=ProtoSkipper-{#MyAppVersion}-Setup
SetupIconFile=protoskipper.ico
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
; Minimum Windows 10
MinVersion=10.0.17763
PrivilegesRequiredOverridesAllowed=dialog
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64

; Reproducible: fix timestamp if SOURCE_DATE_EPOCH is set
; (Inno Setup itself does not support SOURCE_DATE_EPOCH natively;
;  use a wrapper script that patches the output binary if needed)

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"
Name: "addtopath";   Description: "Add ProtoSkipper CLI to system PATH"; GroupDescription: "CLI integration"

[Files]
; Frozen application bundle from PyInstaller
Source: "..\..\dist\ProtoSkipper\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}";          Filename: "{app}\{#MyAppExeName}"
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}";   Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Registry]
; Add CLI to PATH when "addtopath" task is selected
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment";
    ValueType: expandsz; ValueName: "Path";
    ValueData: "{olddata};{app}";
    Check: NeedsAddPath(ExpandConstant('{app}'));
    Tasks: addtopath

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
function NeedsAddPath(Param: string): boolean;
var
  OrigPath: string;
begin
  if not RegQueryStringValue(HKEY_LOCAL_MACHINE,
    'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
    'Path', OrigPath)
  then begin
    Result := True;
    exit;
  end;
  Result := Pos(';' + Param + ';', ';' + OrigPath + ';') = 0;
end;
